Use default credentials for a Nominatim 3.1 Docker image; provides a failing test for a likely change in the place name function.
OsmPlacesSourceTest > canExtractDisplayAddressForPlace STANDARD_ERROR
    org.postgresql.util.PSQLException: ERROR: function get_address_by_language(bigint, text[]) does not exist
      Hint: No function matches the given name and argument types. You might need to add explicit type casts.