Non empty guard needs to account for the non empty name filter.
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;